### ISSUE TITLE
Using coverage before it's installed

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/FcRegression.jl#250]
Is there a reason you need to install FFTW specifically for the coverage analysis? This is loading coverage before it's installed, so the build is failing.

https://github.com/meyer-lab/FcgR.jl/blob/2a10afee9e01b80d4099adcaadbeaa34caae0bac/makefile#L48

**Comment by aarmey** [comment]
If FFTW is a dependency it should go in the package.

**Comment by cyrillustan** [comment]
Last week the build kept failing. The consoles message said Julia needs FFTW built to run, and this worked. I'll change it back and see if the build still fails.

**Comment by aarmey** [comment]
Strange. Let me know if it fails after switching back.
